[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_SHOPIFY_ACCESS_TOKEN = "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"
  VITE_SHOPIFY_STORE_URL = "1d8ac2-1f.myshopify.com"
  VITE_SHOPIFY_API_KEY = "11c6d1d0936e73524a0e6df63919e77b"
  VITE_SHOPIFY_API_SECRET = "fedbda17cf840554a0598c23ceba0b70"
  VITE_APPMAX_API_KEY = "9DAC4B41-6C39A6A1-69FA157F-F8CF3D26"
  VITE_APPMAX_SECRET_KEY = "$2y$10$iORVz0iZfy45evKPY7gyAeV4KGmjeLrmtDSEhLDPaR0qLlOQUMaJ"
  VITE_FB_APP_ID = "1364226285028583"
  VITE_FB_BUSINESS_ID = "317173661178378"
  VITE_FB_ACCESS_TOKEN = "EAAJGXh10g8wBOysBjX8k7GciQnk9kBnPrKRbzEs0xMYZCJS7zwI7sbbccZBbjR5paEWZAC4936b5twzl7GxH9NqVt3JcUMnZCo9RcwaZB34IG7mdLJ0IsKMAejDhz9AdCRxUujA1whVhGl4QZCG3NNIsjROVlMU95DXvT2JsIu4bDEr5rZBmYbdqHKmhBgWRRj2OQXY2omL"
  VITE_FB_AD_ACCOUNT_ID = "1048482983703833"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Shopify-Access-Token"

[dev]
  framework = "vite"

[[plugins]]
  package = "@netlify/plugin-lighthouse"