// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbnmnntzdhagkxsgltgm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impibm1ubnR6ZGhhZ2t4c2dsdGdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NTk2OTAsImV4cCI6MjA2MDIzNTY5MH0.3vZN2v-ttl0mSsXvymj3Z2i_7hbX_rc7LhSjkao196A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);